### 1. @RequestParam - Query String 각각 받기
GET localhost:8080/api/v1/menus?keyword=coffee&categoryCode=2&page=1

### 2. @RequestParam - Query String 전체 받기
GET localhost:8080/api/v1/menus/search?keyword=coffee&categoryCode=2&page=1

### 3. @PathVariable - URL 경로 값 받기
GET localhost:8080/api/v1/menus/5

### 4. @RequestBody - JSON 요청 본문을 DTO로 받기
POST localhost:8080/api/v1/menus
Content-Type: application/json

{
  "name" : "아이스 아메리카노",
  "price" : 5000,
  "categoryCode": 2,
  "orderableStatus": "Y"
}

### 5. @RequestBody - 요청 본문을 문자열로 그대로 받기
POST localhost:8080/api/v1/menus/raw
Content-Type: text/plain

plain text

### 6. @RequestHeader, @CookieValue
GET localhost:8080/api/v1/menus/request-info
User-Agent: Intellij HTTP Client
Cookie: JSESSIONID=test-session-id

### 7. HTTPSession - session에 값 저장
POST localhost:8080/api/v1/menus/session?id=user01

### 8. HTTPSession - session 값 조회
GET localhost:8080/api/v1/menus/session

### 9. HTTPSession - session 만료
DELETE localhost:8080/api/v1/menus/session