### 1. 메뉴 목록 조회
GET localhost:8080/api/v1/menus

### 2. 메뉴 등록
POST localhost:8080/api/v1/menus

### 3. 메뉴 수정
PUT localhost:8080/api/v1/menus/3

### 4. 메뉴 삭제
DELETE localhost:8080/api/v1/menus/2

### 5. 주문 목록 조회
GET localhost:8080/api/v1/orders

### 6. 주문 상세 조회
GET localhost:8080/api/v1/orders/1