spring:
  application:
    name: springsecurity
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cqrs
    username: spcamp
    password: spcamp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.ohgiraffers.springsecurity.query.dto
jwt:
  secret: PpI+H5IQD/Qy/iXz3gOAmQpiKMrUPxrj8vdT7i5O1qXKFqv7Zad6Aw+GZVwa/27WAi54CSZ7TeREuO94GruX+A==
  expiration: 1800000   #30분 (access token)
  refresh-expiration: 604800000 # 7일(refresh token)
