CREATE TABLE TEAM_INFO(
	TEAM_CODE INT PRIMARY KEY AUTO_INCREMENT,
    TEAM_NAME VARCHAR(100),
    TEAM_DETAIL VARCHAR(500),
    USE_YN CHAR(2) DEFAULT 'Y',
    CHECK(USE_YN IN ('Y','N'))
)ENGINE=INNODB;

DESC TEAM_INFO;

CREATE TABLE MEMBER_INFO(
	MEMBER_CODE INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_NAME VARCHAR(70),
    BIRTH_DATE DATE,
    DIVISION_CODE CHAR(2),
    DETAIL_INFO VARCHAR(500),
    CONTACT VARCHAR(50),
    TEAM_CODE INT,
    ACTIVE_STATUS CHAR(2) DEFAULT 'Y',
    CHECK(ACTIVE_STATUS IN ('Y', 'N', 'H')),
    FOREIGN KEY (TEAM_CODE) REFERENCES TEAM_INFO(TEAM_CODE)
)ENGINE=INNODB;

DESC MEMBER_INFO;