# Q1
CREATE TABLE TEAM_INFO(
	TEAM_CODE INT PRIMARY KEY AUTO_INCREMENT,
    TEAM_NAME VARCHAR(100),
    TEAM_DETAIL VARCHAR(500),
    USE_YN CHAR(2) DEFAULT 'Y',
    CHECK(USE_YN IN ('Y','N'))
)ENGINE=INNODB;

# Q2
INSERT INTO TEAM_INFO(TEAM_CODE, TEAM_NAME, TEAM_DETAIL)
VALUES(NULL, '음악감상부', '클래식 및 재즈 음악을 감상하는 사람들의 모임');

INSERT INTO TEAM_INFO VALUES(NULL, '맛집탐방부', '맛집을 찾아다니는 사람들의 모임', 'N');
INSERT INTO TEAM_INFO(TEAM_CODE, TEAM_NAME)
VALUES(NULL, '행복찾기부');

DESC TEAM_INFO;

SELECT * FROM TEAM_INFO;

CREATE TABLE MEMBER_INFO(
	MEMBER_CODE INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_NAME VARCHAR(70),
    BIRTH_DATE DATE,
    DIVISION_CODE CHAR(2),
    DETAIL_INFO VARCHAR(500),
    CONTACT VARCHAR(50),
    TEAM_CODE INT,
    ACTIVE_STATUS CHAR(2) DEFAULT 'Y',
    CHECK(ACTIVE_STATUS IN ('Y', 'N', 'H')),
    FOREIGN KEY (TEAM_CODE) REFERENCES TEAM_INFO(TEAM_CODE)
)ENGINE=INNODB;

DESC MEMBER_INFO;

SELECT * FROM MEMBER_INFO;

INSERT INTO MEMBER_INFO VALUES(NULL, '송가인', '1990-01-30', 1, '안녕하세요 송가인입니다~', '010-9494-9494', 1, 'H');
INSERT INTO MEMBER_INFO(MEMBER_CODE, MEMBER_NAME, BIRTH_DATE, DETAIL_INFO, CONTACT, TEAM_CODE)
			VALUES(NULL, '임영웅', '1992-05-03', '국민아들 임영웅입니다~', 'hero@trot.com', 1);
INSERT INTO MEMBER_INFO(MEMBER_CODE, MEMBER_NAME, CONTACT, TEAM_CODE)
			VALUES(NULL, '태진아', '(1급 기밀)',3);
            
# Q3
SELECT
	JOB_NAME,
    d.DEPT_TITLE,
    e.EMP_NAME
FROM employee e
JOIN job j ON e.JOB_CODE = j.JOB_CODE
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
WHERE
	DEPT_TITLE = '기술지원부'
UNION
SELECT
	JOB_NAME,
    d.DEPT_TITLE,
    e.EMP_NAME
FROM employee e
JOIN job j ON e.JOB_CODE = j.JOB_CODE
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
WHERE
	DEPT_TITLE = '인사관리부' AND JOB_NAME = '사원';

SELECT
	COUNT(*)
FROM(
SELECT
    e.EMP_NAME
FROM employee e
JOIN job j ON e.JOB_CODE = j.JOB_CODE
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
WHERE
	DEPT_TITLE = '기술지원부' AND JOB_NAME = '대리'
UNION
SELECT
    e.EMP_NAME
FROM employee e
JOIN job j ON e.JOB_CODE = j.JOB_CODE
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
WHERE
	DEPT_TITLE = '인사관리부' AND JOB_NAME = '사원'
UNION
SELECT
    e.EMP_NAME
FROM employee e
JOIN job j ON e.JOB_CODE = j.JOB_CODE
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
WHERE
	DEPT_TITLE LIKE '%영업%' AND JOB_NAME = '부장') AS temp;
    
# Q4-1
SELECT 
	e.EMP_ID,
    e.EMP_NAME,
    e.PHONE,
    d.DEPT_TITLE,
    j.JOB_NAME,
	e.SALARY
FROM 
	employee e
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
JOIN job j ON e.JOB_CODE = j.JOB_CODE
WHERE
	d.DEPT_TITLE NOT LIKE '%영업%' AND j.JOB_NAME IN ('대리','차장')
UNION ALL
SELECT
	e.EMP_ID,
    e.EMP_NAME,
    e.PHONE,
    d.DEPT_TITLE,
    j.JOB_NAME,
	e.SALARY
FROM 
	employee e
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
JOIN job j ON e.JOB_CODE = j.JOB_CODE
WHERE
	e.SALARY BETWEEN 2000000 AND 3000000;
    
# Q4-2
SELECT
	temp.EMP_NAME,
    temp.SALARY,
    COUNT(*)
FROM (
SELECT 
	e.EMP_ID,
    e.EMP_NAME,
    e.PHONE,
    d.DEPT_TITLE,
    j.JOB_NAME,
	e.SALARY
FROM 
	employee e
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
JOIN job j ON e.JOB_CODE = j.JOB_CODE
WHERE
	d.DEPT_TITLE NOT LIKE '%영업%' AND j.JOB_NAME IN ('대리','차장')
UNION ALL
SELECT
	e.EMP_ID,
    e.EMP_NAME,
    e.PHONE,
    d.DEPT_TITLE,
    j.JOB_NAME,
	e.SALARY
FROM 
	employee e
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
JOIN job j ON e.JOB_CODE = j.JOB_CODE
WHERE
	e.SALARY BETWEEN 2000000 AND 3000000) As temp
GROUP BY
	EMP_NAME,
    SALARY;

# Q4-3
SELECT
	temp.EMP_NAME,
    temp.SALARY,
    COUNT(*)
FROM (
SELECT 
	e.EMP_ID,
    e.EMP_NAME,
    e.PHONE,
    d.DEPT_TITLE,
    j.JOB_NAME,
	e.SALARY
FROM 
	employee e
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
JOIN job j ON e.JOB_CODE = j.JOB_CODE
WHERE
	d.DEPT_TITLE NOT LIKE '%영업%' AND j.JOB_NAME IN ('대리','차장')
UNION ALL
SELECT
	e.EMP_ID,
    e.EMP_NAME,
    e.PHONE,
    d.DEPT_TITLE,
    j.JOB_NAME,
	e.SALARY
FROM 
	employee e
JOIN department d ON e.DEPT_CODE = d.DEPT_ID
JOIN job j ON e.JOB_CODE = j.JOB_CODE
WHERE
	e.SALARY BETWEEN 2000000 AND 3000000) As temp
GROUP BY
	EMP_NAME,
    SALARY
ORDER BY
	COUNT(*) DESC,
    SALARY DESC
LIMIT
	3;


    
    
	